package io.github.rodrigofabreu.signalhub.user;

import java.util.UUID;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

/** A user as an admin's device sees them: who they are on the server, never a key or a token. */
@Schema(
    name = "DetailedUser",
    description =
        "A user, as an admin's device sees them: ID, name, role and how many devices they have.")
public record DetailedUser(
    @Schema(
            required = true,
            description = "Canonical user ID, generated by SignalHub.",
            examples = "01997d5e-8a3c-7b1e-9f2a-4c6d8e0f1a2b")
        UUID id,
    @Schema(required = true, examples = "Anna") String name,
    @Schema(required = true) Role role,
    @Schema(
            required = true,
            description = "How many of the user's devices are not revoked.",
            examples = "2")
        long activeDevices,
    @Schema(
            required = true,
            description =
                "Whether the user has ever had a device, revoked or not. False for a user who was"
                    + " invited and has not paired yet.")
        boolean hasPaired) {}
