package io.github.rodrigofabreu.signalhub.user;

import java.util.UUID;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

/**
 * A user as other users see them: an ID to choose them by, and a name. Never their role, so the
 * admins are not told apart from the rest.
 */
@Schema(name = "NamedUser", description = "A user, as other users see them: ID and name only.")
public record NamedUser(
    @Schema(
            required = true,
            description = "Canonical user ID, generated by SignalHub.",
            examples = "01997d5e-8a3c-7b1e-9f2a-4c6d8e0f1a2b")
        UUID id,
    @Schema(required = true, examples = "Anna") String name) {

  public static NamedUser of(UserRef user) {
    return new NamedUser(user.id(), user.name());
  }
}
