package io.github.rodrigofabreu.signalhub.user;

import java.util.UUID;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

/** A producer a user owns, as an admin's device sees it: no key, no event, no allow-list. */
@Schema(
    name = "PersonProducer",
    description = "A producer owned by a user: ID, name, visibility and whether it is disabled.")
public record PersonProducer(
    @Schema(
            required = true,
            description = "Canonical producer ID, generated by SignalHub.",
            examples = "01997d5e-8a3c-7b1e-9f2a-4c6d8e0f1a2b")
        UUID id,
    @Schema(required = true, examples = "ci-build-runner") String name,
    @Schema(required = true, description = "PUBLIC or PRIVATE.") String visibility,
    @Schema(required = true, description = "Whether the producer is disabled.") boolean disabled) {}
