package io.github.rodrigofabreu.signalhub.user;

import java.util.UUID;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

/** Who a user is, as other resources show them: ID, name and role. */
@Schema(name = "UserRef", description = "A user: their ID, name and role.")
public record UserRef(
    @Schema(
            required = true,
            description = "Canonical user ID, generated by SignalHub.",
            examples = "01997d5e-8a3c-7b1e-9f2a-4c6d8e0f1a2b")
        UUID id,
    @Schema(required = true, examples = "Anna") String name,
    @Schema(required = true) Role role) {

  public boolean admin() {
    return role == Role.ADMIN;
  }
}
