package io.github.rodrigofabreu.signalhub.user;

import java.time.Instant;
import java.util.List;
import java.util.UUID;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

/** A user as the management API shows them: their devices, producers and subscriptions. */
@Schema(
    name = "User",
    description =
        "A user of this SignalHub server, with their devices, the producers they own and the"
            + " producers they are subscribed to. Never a key or a push token.")
public record UserResponse(
    @Schema(
            required = true,
            description = "Canonical user ID, generated by SignalHub.",
            examples = "01997d5e-8a3c-7b1e-9f2a-4c6d8e0f1a2b")
        UUID id,
    @Schema(required = true, examples = "Anna") String name,
    @Schema(required = true, description = "What the user may do with devices.") Role role,
    @Schema(required = true, examples = "2026-09-25T12:00:00.123456Z") Instant createdAt,
    @Schema(
            description =
                "When the user was revoked; null while active. Revoking a user revokes their"
                    + " devices and disables their producers.")
        Instant revokedAt,
    @Schema(required = true, description = "The user's devices, oldest first.")
        List<Device> devices,
    @Schema(required = true, description = "The producers the user owns, by name.")
        List<Producer> producers,
    @Schema(required = true, description = "The producers the user receives events from.")
        List<Producer> subscriptions) {

  public UserResponse {
    devices = List.copyOf(devices);
    producers = List.copyOf(producers);
    subscriptions = List.copyOf(subscriptions);
  }

  @Schema(name = "UserDevice", description = "One of a user's devices.")
  public record Device(
      @Schema(required = true) UUID id,
      @Schema(required = true, examples = "Pixel 8") String name,
      @Schema(description = "When the device was revoked; null while active.") Instant revokedAt) {}

  @Schema(name = "UserProducer", description = "A producer, as a user's lists show it.")
  public record Producer(
      @Schema(required = true) UUID id,
      @Schema(required = true, examples = "ci-build-runner") String name,
      @Schema(required = true, description = "PUBLIC or PRIVATE.") String visibility,
      @Schema(description = "When the producer was disabled; null while enabled.")
          Instant disabledAt) {}
}
