package io.github.rodrigofabreu.signalhub.client;

import java.time.Instant;
import java.util.UUID;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

/** A registered client, without its key or push token. */
@Schema(name = "Client", description = "A registered client installation.")
public record ClientResponse(
    @Schema(
            required = true,
            description = "Canonical client ID, generated by SignalHub.",
            examples = "01997d5e-8a3c-7b1e-9f2a-4c6d8e0f1a2b")
        UUID id,
    @Schema(required = true, examples = "Pixel 8") String name,
    @Schema(required = true, examples = "2026-09-25T12:00:00.123456Z") Instant createdAt,
    @Schema(
            description =
                "When the client was revoked; null while it is active. A revoked client cannot"
                    + " authenticate and receives no pushes.")
        Instant revokedAt,
    @Schema(description = "Where pushes for this client go; null if it has none.")
        PushTarget pushTarget,
    @Schema(required = true, description = "Which events are pushed to the client.")
        PushPreferences pushPreferences) {

  @Schema(
      name = "PushTarget",
      description = "A client's push target. The token itself is never returned.")
  public record PushTarget(
      @Schema(required = true, examples = "fcm") String provider,
      @Schema(
              required = true,
              description = "When the client last set its push target.",
              examples = "2026-09-25T12:00:00.123456Z")
          Instant updatedAt) {}
}
