package io.github.rodrigofabreu.signalhub.client;

import io.github.rodrigofabreu.signalhub.user.UserRef;
import java.time.Instant;
import java.util.UUID;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

/**
 * A client as the operator reads it through the management API: every field of {@link
 * ClientResponse} and its latest push results. Clients never read their own push results.
 */
@Schema(
    name = "ManagedClient",
    description =
        "A registered client installation as the management API shows it: the fields of Client"
            + " and its latest push results.")
public record ManagedClientResponse(
    @Schema(
            required = true,
            description = "Canonical client ID, generated by SignalHub.",
            examples = "01997d5e-8a3c-7b1e-9f2a-4c6d8e0f1a2b")
        UUID id,
    @Schema(required = true, examples = "Pixel 8") String name,
    @Schema(
            required = true,
            description =
                "Whether the client is an admin device: exactly when its user is an ADMIN.")
        boolean admin,
    @Schema(required = true, description = "The user the client belongs to, with their role.")
        UserRef user,
    @Schema(required = true, examples = "2026-09-25T12:00:00.123456Z") Instant createdAt,
    @Schema(
            description =
                "When the client was revoked; null while it is active. A revoked client cannot"
                    + " authenticate and receives no pushes.")
        Instant revokedAt,
    @Schema(description = "Where pushes for this client go; null if it has none.")
        ClientResponse.PushTarget pushTarget,
    @Schema(required = true, description = "Which events are pushed to the client.")
        PushPreferences pushPreferences,
    @Schema(required = true, description = "The client's latest push results.")
        PushStatus pushStatus) {

  static ManagedClientResponse of(ClientResponse client, PushStatus pushStatus) {
    return new ManagedClientResponse(
        client.id(),
        client.name(),
        client.admin(),
        client.user(),
        client.createdAt(),
        client.revokedAt(),
        client.pushTarget(),
        client.pushPreferences(),
        pushStatus);
  }
}
