package io.github.rodrigofabreu.signalhub.producer;

import io.github.rodrigofabreu.signalhub.user.NamedUser;
import java.time.Instant;
import java.util.List;
import java.util.UUID;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

/** A producer as its owner sees it from a device: its keys by prefix, never the keys. */
@Schema(
    name = "OwnProducer",
    description =
        "A producer the caller owns, with its keys (never the keys themselves) and who is allowed"
            + " on it.")
public record OwnProducerResponse(
    @Schema(
            required = true,
            description = "Canonical producer ID, generated by SignalHub.",
            examples = "01997d5e-8a3c-7b1e-9f2a-4c6d8e0f1a2b")
        UUID id,
    @Schema(required = true, examples = "ci-build-runner") String name,
    @Schema(required = true, examples = "2026-09-25T12:00:00.123456Z") Instant createdAt,
    @Schema(
            description =
                "When the producer was disabled; null while enabled. A disabled producer cannot"
                    + " authenticate with any of its keys.")
        Instant disabledAt,
    @Schema(
            required = true,
            description =
                "Whether the operator disabled it (or its owner was revoked): then only the"
                    + " operator enables it again. False while enabled or when its owner disabled"
                    + " it.")
        boolean disabledByOperator,
    @Schema(
            description =
                "When SignalHub received the producer's most recent event that is still stored;"
                    + " null when none is.",
            examples = "2026-09-30T08:15:00.123456Z")
        Instant lastEventAt,
    @Schema(required = true, description = "All keys ever issued, oldest first.") List<Key> keys,
    @Schema(
            required = true,
            description =
                "PUBLIC: every user may see it and subscribe. PRIVATE: its owner and the users"
                    + " on its allow-list. New producers are PRIVATE.")
        Visibility visibility,
    @Schema(
            required = true,
            description =
                "The users on the allow-list of a private producer, besides its owner, by name."
                    + " Kept, but without effect, while the producer is public.")
        List<NamedUser> allowedUsers,
    @Schema(
            required = true,
            description =
                "Whether the caller receives this producer's events (the owner may stop).")
        boolean subscribed) {

  public OwnProducerResponse {
    keys = List.copyOf(keys);
    allowedUsers = List.copyOf(allowedUsers);
  }

  @Schema(name = "OwnApiKey", description = "An issued API key. The key itself is never returned.")
  public record Key(
      @Schema(required = true, description = "Key ID, also embedded in the key itself.") UUID id,
      @Schema(
              required = true,
              description =
                  "How the key starts: its format and ID, enough to tell keys apart. Not a secret.",
              examples = "shpk1_3f1c0b8e5d2a4c7e9b610a8d4e2f7c13")
          String prefix,
      @Schema(required = true, examples = "2026-09-25T12:00:00.123456Z") Instant createdAt,
      @Schema(
              description =
                  "When the key last authenticated a publish request, to within a minute (it is"
                      + " recorded at most once a minute); null until it has.",
              examples = "2026-09-30T08:15:00.123456Z")
          Instant lastUsedAt,
      @Schema(description = "When the key was revoked; null while it is valid.")
          Instant revokedAt) {}
}
