package io.github.rodrigofabreu.signalhub.producer;

import java.time.Instant;
import java.util.List;
import java.util.UUID;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

/** A registered producer and its API keys (never the keys themselves), for the management API. */
@Schema(name = "Producer", description = "A registered producer and its API keys.")
public record ProducerResponse(
    @Schema(
            required = true,
            description = "Canonical producer ID, generated by SignalHub.",
            examples = "01997d5e-8a3c-7b1e-9f2a-4c6d8e0f1a2b")
        UUID id,
    @Schema(required = true, examples = "ci-build-runner") String name,
    @Schema(required = true, examples = "2026-09-25T12:00:00.123456Z") Instant createdAt,
    @Schema(
            description =
                "When the producer was disabled; null while enabled. A disabled producer cannot"
                    + " authenticate with any of its keys.")
        Instant disabledAt,
    @Schema(required = true, description = "All keys ever issued, oldest first.")
        List<ApiKey> keys) {

  public ProducerResponse {
    keys = List.copyOf(keys);
  }

  @Schema(name = "ApiKey", description = "An issued API key. The key itself is never returned.")
  public record ApiKey(
      @Schema(
              required = true,
              description = "Key ID, also embedded in the key itself.",
              examples = "3f1c0b8e-5d2a-4c7e-9b61-0a8d4e2f7c13")
          UUID id,
      @Schema(required = true, examples = "2026-09-25T12:00:00.123456Z") Instant createdAt,
      @Schema(description = "When the key was revoked; null while it is valid.")
          Instant revokedAt) {}
}
