package io.github.rodrigofabreu.signalhub.producer;

import io.github.rodrigofabreu.signalhub.user.UserRef;
import java.time.Instant;
import java.util.List;
import java.util.UUID;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

/** A registered producer and its API keys (never the keys themselves), for the management API. */
@Schema(name = "Producer", description = "A registered producer and its API keys.")
public record ProducerResponse(
    @Schema(
            required = true,
            description = "Canonical producer ID, generated by SignalHub.",
            examples = "01997d5e-8a3c-7b1e-9f2a-4c6d8e0f1a2b")
        UUID id,
    @Schema(required = true, examples = "ci-build-runner") String name,
    @Schema(required = true, examples = "2026-09-25T12:00:00.123456Z") Instant createdAt,
    @Schema(
            description =
                "When the producer was disabled; null while enabled. A disabled producer cannot"
                    + " authenticate with any of its keys.")
        Instant disabledAt,
    @Schema(
            description =
                "When SignalHub received the producer's most recent event that is still stored;"
                    + " null when none is (it never published, or retention deleted its events).",
            examples = "2026-09-30T08:15:00.123456Z")
        Instant lastEventAt,
    @Schema(required = true, description = "All keys ever issued, oldest first.") List<ApiKey> keys,
    @Schema(required = true, description = "The user who owns the producer.") UserRef owner,
    @Schema(
            required = true,
            description =
                "PUBLIC: every user may see it and subscribe. PRIVATE: its owner and the users"
                    + " on its allow-list. New producers are PRIVATE.")
        Visibility visibility,
    @Schema(
            required = true,
            description =
                "The users on the allow-list of a private producer, besides its owner, by name."
                    + " Kept, but without effect, while the producer is public.")
        List<UserRef> allowedUsers) {

  public ProducerResponse {
    keys = List.copyOf(keys);
    allowedUsers = List.copyOf(allowedUsers);
  }

  @Schema(name = "ApiKey", description = "An issued API key. The key itself is never returned.")
  public record ApiKey(
      @Schema(
              required = true,
              description = "Key ID, also embedded in the key itself.",
              examples = "3f1c0b8e-5d2a-4c7e-9b61-0a8d4e2f7c13")
          UUID id,
      @Schema(required = true, examples = "2026-09-25T12:00:00.123456Z") Instant createdAt,
      @Schema(description = "When the key was revoked; null while it is valid.")
          Instant revokedAt) {}
}
