"""Database engine, ORM base class, and request-scoped sessions."""

from collections.abc import Iterator
from typing import Annotated

from fastapi import Depends, Request
from sqlalchemy import Engine, MetaData, create_engine
from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker

# Bounds how long a request (notably the readiness check) waits for an
# unreachable database, instead of the operating system's TCP timeout.
CONNECT_TIMEOUT_SECONDS = 5

# Deterministic constraint names keep autogenerated Alembic migrations stable
# and make constraints addressable by name in later migrations.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Base class for ORM models. Alembic compares migrations against its metadata."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def create_db_engine(database_url: str) -> Engine:
    # pool_pre_ping replaces connections the server has closed (for example
    # after a database restart) instead of failing the next request with them.
    return create_engine(
        database_url,
        pool_pre_ping=True,
        connect_args={"connect_timeout": CONNECT_TIMEOUT_SECONDS},
    )


def create_session_factory(engine: Engine) -> sessionmaker[Session]:
    # Sessions commit before the response is serialized, so loaded objects
    # must stay readable after commit without reloading from the database.
    return sessionmaker(engine, expire_on_commit=False)


def get_session(request: Request) -> Iterator[Session]:
    """Yield a session whose transaction commits if the request handler
    succeeds and rolls back if it raises."""
    with request.app.state.session_factory.begin() as session:
        yield session


# scope="function" commits before the response is sent, so a client is never
# told that a request succeeded when its transaction failed to commit.
DbSession = Annotated[Session, Depends(get_session, scope="function")]
