package io.github.rodrigofabreu.signalhub.event;

import com.fasterxml.jackson.annotation.JsonRawValue;
import java.time.Instant;
import java.util.UUID;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

/** The canonical representation of a stored event, as returned by the API. */
@Schema(name = "Event", description = "A stored event in its canonical form.")
public record EventResponse(
    @Schema(
            required = true,
            description = "Canonical event ID, generated by SignalHub (UUIDv7).",
            examples = "01997d5e-8a3c-7b1e-9f2a-4c6d8e0f1a2b")
        UUID id,
    @Schema(
            required = true,
            description =
                "The producer that published the event, as authenticated by its API key. Never"
                    + " taken from the request body.")
        Producer producer,
    @Schema(examples = "signalhub") String context,
    @Schema(required = true) Category category,
    @Schema(required = true) Severity severity,
    @Schema(required = true, examples = "Nightly build failed") String title,
    @Schema(examples = "3 of 412 tests failed on main.") String message,
    @Schema(
            required = true,
            ref = "JsonObject",
            description = "Producer metadata as submitted; an empty object when none was sent.")
        // Already-valid JSON text from PostgreSQL, written into the response as is.
        @JsonRawValue
        String metadata,
    @Schema(
            description = "Producer-supplied occurrence time, normalized to UTC; null if not sent.",
            examples = "2026-09-25T12:03:00Z")
        Instant occurredAt,
    @Schema(
            required = true,
            description = "Canonical time SignalHub accepted and stored the event, in UTC.",
            examples = "2026-09-25T12:03:01.482113Z")
        Instant createdAt) {

  @Schema(name = "EventProducer", description = "The producer that published an event.")
  public record Producer(
      @Schema(
              required = true,
              description = "Canonical producer ID.",
              examples = "01997d5d-1c2b-7a40-8e3f-5b6c7d8e9f00")
          UUID id,
      @Schema(required = true, description = "Producer name.", examples = "ci-build-runner")
          String name) {}
}
